# Generated by Django 3.2.6 on 2021-08-31 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0005_alter_produto_descricao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='tipo',
            field=models.CharField(choices=[('', 'Selecione:'), ('Cosmético', 'Cosmético'), ('Industrial', 'Industrial'), ('Alimentício', 'Alimentício')], max_length=100),
        ),
    ]
