# Generated by Django 3.2.6 on 2021-08-31 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0006_alter_produto_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='estado',
            field=models.IntegerField(choices=[('Disponível', 'Disponível'), ('Vendido', 'Vendido')], default=1, max_length=12),
            preserve_default=False,
        ),
    ]
